import os
import traceback

import config
from helpers import Emoji, Tools, animate_proses
from logs import logger


BLACKBOX_CHAT_URL = "https://enterprise.blackbox.ai/v1/messages"


async def blackbox_request(messages):
    headers = {
        "Authorization": f"Bearer {config.API_BLACKBOX}",
        "Content-Type": "application/json",
        "anthropic-version": "2023-06-01",
    }

    payload = {
        "model": "blackboxai/anthropic/claude-sonnet-4.5",
        "max_tokens": 4096,
        "messages": messages,
    }

    r = await Tools.fetch.post(
        BLACKBOX_CHAT_URL,
        headers=headers,
        json=payload
    )

    if r.status_code != 200:
        raise Exception(
            f"BlackBox Error {r.status_code}: {r.text}"
        )

    data = r.json()

    return data["content"][0]["text"]


async def blackbox_cmd(client, message):
    em = Emoji(client)
    await em.get()

    proses = await animate_proses(
        message,
        em.proses
    )

    prompt = client.get_text(message)

    if not prompt:
        return await proses.edit(
            f"{em.gagal}**Please give a prompt.**"
        )

    try:
        result = await blackbox_request(
            [
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )

        if len(result) > 4096:
            file_name = "blackbox_result.txt"

            with open(
                file_name,
                "w",
                encoding="utf-8"
            ) as f:
                f.write(result)

            await message.reply_document(
                file_name,
                caption=f"{em.sukses} Generated by Claude Sonnet 4.5"
            )

            os.remove(file_name)

            return await proses.delete()

        return await proses.edit(
            f"<blockquote>{result}</blockquote>"
        )

    except Exception as e:
        logger.error(traceback.format_exc())

        return await proses.edit(
            f"{em.gagal}**Terjadi kesalahan:**\n`{e}`"
        )


async def claude_cmd(client, message):
    em = Emoji(client)
    await em.get()

    proses = await animate_proses(
        message,
        em.proses
    )

    prompt = client.get_text(message)

    if not prompt:
        return await proses.edit(
            f"{em.gagal}**Masukkan prompt.**"
        )

    chat_id = message.chat.id

    system_prompt = (
        "Kamu adalah asisten AI paling canggih. "
        "Gunakan bahasa Indonesia yang santai "
        "kecuali user memakai bahasa lain."
    )

    history = [
        {
            "role": "user",
            "content": (
                f"System instruction:\n{system_prompt}\n\n"
                f"{prompt}"
            )
        }
    ]

    while True:
        try:
            result = await blackbox_request(history)

            if len(result) > 4096:
                file_name = "claude_chat.txt"

                with open(
                    file_name,
                    "w",
                    encoding="utf-8"
                ) as f:
                    f.write(result)

                reply = await message._client.send_document(
                    chat_id,
                    file_name
                )

                os.remove(file_name)

                next_message = await message._client.ask(
                    chat_id,
                    "**Chat with Claude Sonnet 4.5**\n\n"
                    f"Question:\n{prompt}\n\n"
                    "Ketik `stopped ask` untuk mengakhiri.",
                    reply_to_message_id=reply.id,
                    timeout=300
                )

            else:
                next_message = await message._client.ask(
                    chat_id,
                    "**Chat with Claude Sonnet 4.5**\n\n"
                    f"Question:\n{prompt}\n\n"
                    f"Answer:\n<blockquote>{result}</blockquote>\n\n"
                    "Ketik `stopped ask` untuk mengakhiri.",
                    timeout=300
                )

            if not next_message.text:
                continue

            if next_message.text.lower() == "stopped ask":
                await next_message.reply(
                    "**Conversation ended.**"
                )
                break

            history.append(
                {
                    "role": "assistant",
                    "content": result
                }
            )

            history.append(
                {
                    "role": "user",
                    "content": next_message.text
                }
            )

            prompt = next_message.text

        except Exception:
            logger.error(traceback.format_exc())

            return await proses.edit(
                "<b>Please try again later.</b>"
            )