import asyncio
import traceback

import config
from helpers import Emoji, Tools, animate_proses
from logs import logger


BLACKBOX_CHAT_URL = "https://api.blackbox.ai/chat/completions"


async def blackbox_request(messages):

    headers = {
        "Authorization": f"Bearer {config.API_BLACKBOX}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": "blackboxai/x-ai/grok-code-fast-1:free",
        "messages": messages,
        "temperature": 0.3,
        "max_tokens": 512
    }


    for retry in range(2):

        r = await Tools.fetch.post(
            BLACKBOX_CHAT_URL,
            headers=headers,
            json=payload
        )


        if r.status_code == 200:

            data = r.json()

            return data["choices"][0]["message"]["content"]


        if r.status_code == 429:

            await asyncio.sleep(
                5
            )

            continue


        raise Exception(
            f"BlackBox Error {r.status_code}: {r.text}"
        )


    return "⚠️ AI sedang limit, coba lagi nanti."



async def blackbox_cmd(client, message):

    em = Emoji(client)
    await em.get()


    proses = await animate_proses(
        message,
        em.proses
    )


    prompt = client.get_text(message)


    if not prompt:

        return await proses.edit(
            f"{em.gagal} Masukkan prompt."
        )


    try:

        result = await blackbox_request(
            [
                {
                    "role": "system",
                    "content":
                    "AI coding assistant. "
                    "Jawab singkat dan jelas."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )


        if len(result) > 4096:

            file_name = "blackbox_result.txt"

            with open(
                file_name,
                "w",
                encoding="utf-8"
            ) as f:
                f.write(result)


            await message.reply_document(
                file_name,
                caption=f"{em.sukses} Generated by Grok"
            )


            return await proses.delete()



        return await proses.edit(
            f"<blockquote>{result}</blockquote>"
        )


    except Exception as e:

        logger.error(
            traceback.format_exc()
        )


        return await proses.edit(
            f"{em.gagal} Error:\n`{e}`"
        )




async def deepseek_cmd(client, message):

    em = Emoji(client)
    await em.get()


    proses = await animate_proses(
        message,
        em.proses
    )


    prompt = client.get_text(message)


    if not prompt:

        return await proses.edit(
            f"{em.gagal} Masukkan prompt."
        )


    chat_id = message.chat.id


    history = [
        {
            "role": "system",
            "content":
            "AI assistant."
        },
        {
            "role": "user",
            "content": prompt
        }
    ]


    while True:

        try:

            result = await blackbox_request(
                history
            )


            next_message = await message._client.ask(
                chat_id,
                f"🤖 **Grok AI**\n\n"
                f"{result}\n\n"
                "Ketik `stopped ask` untuk selesai.",
                timeout=300
            )


            if (
                next_message.text.lower()
                ==
                "stopped ask"
            ):

                await next_message.reply(
                    "✅ Conversation ended."
                )

                break



            history.append(
                {
                    "role": "assistant",
                    "content": result
                }
            )


            history.append(
                {
                    "role": "user",
                    "content":
                    next_message.text
                }
            )


            # hanya simpan 4 percakapan terakhir
            history = history[-6:]


        except Exception:

            logger.error(
                traceback.format_exc()
            )

            return await proses.edit(
                "❌ Please try again later."
            )