import os
import shutil
import traceback
import uuid

import aiofiles
import aiohttp
from pyrogram.types import InputMediaPhoto

from config import API_MAELYN
from helpers import Bing, Emoji, Tools, animate_proses
from logs import logger

async def brat_cmd(client, message):
    em = Emoji(client)
    await em.get()

    command = message.command[0]
    is_animated = command != "brat"
    prompt = client.get_text(message)

    if not prompt:
        return await message.reply(
            f"{em.gagal}**Please reply to a message containing the prompt!**\n"
            f"Example: `{command} aku ganteng`"
        )

    proses = await animate_proses(message, em.proses)

    try:
        url = "https://api.siputzx.my.id/api/m/brat"

        params = {
            "text": prompt,
            "delay": 500
        }

        response = await Tools.fetch.get(
            url,
            params=params
        )

        if response.status_code != 200:
            raise Exception(
                f"API Error: {response.status_code}"
            )

        content_type = response.headers.get(
            "Content-Type",
            ""
        )

        if "gif" in content_type:
            ext = "gif"
        elif "png" in content_type:
            ext = "png"
        elif "webp" in content_type:
            ext = "webp"
        else:
            ext = "png"

        file_path = f"brat_{uuid.uuid4().hex}.{ext}"

        with open(file_path, "wb") as f:
            f.write(response.content)

        if ext == "gif":
            await client.send_animation(
                chat_id=message.chat.id,
                animation=file_path,
                caption=f"{em.sukses}**Generated by {client.me.mention}**"
            )

        elif ext == "webp":
            await client.send_sticker(
                chat_id=message.chat.id,
                sticker=file_path
            )

        else:
            await client.send_photo(
                chat_id=message.chat.id,
                photo=file_path,
                caption=f"{em.sukses}**Generated by {client.me.mention}**"
            )

        os.remove(file_path)

        await proses.delete()

    except Exception as e:
        await proses.edit(
            f"{em.gagal}**ERROR:**\n`{e}`"
        )

async def bingimg_cmd(client, message):
    emo = Emoji(client)
    await emo.get()

    prompt = client.get_text(message)

    if not prompt:
        return await message.reply(
            f"{emo.gagal}<b>Give the query you want to search!\n\n"
            f"Example:\n<code>{message.text.split()[0]} kucing lucu</code></b>"
        )

    pros = await message.reply(
        f"{emo.proses}<b>Searching image <code>{prompt}</code> ..</b>"
    )

    try:
        api = "https://api.siputzx.my.id/api/s/bimg"

        async with aiohttp.ClientSession() as session:
            async with session.post(
                api,
                json={"query": prompt},
                headers={"Content-Type": "application/json"}
            ) as resp:
                result = await resp.json()

        if not result.get("status"):
            return await pros.edit(
                f"{emo.gagal}<b>Failed get image.</b>"
            )

        imgs = result.get("data", [])

        if not imgs:
            return await pros.edit(
                f"{emo.gagal}<b>Images not found.</b>"
            )

        media_group = []

        for img in imgs[:10]:
            caption = None

            if not media_group:
                caption = (
                    f"{emo.sukses}<b>Bing Image Result</b>\n\n"
                    f"<blockquote>"
                    f"🔎 <b>Query:</b> <code>{prompt}</code>\n"
                    f"🖼️ <b>Result:</b> <code>{len(imgs)}</code> images\n"
                    f"⚡ <b>Source:</b> Bing"
                    f"</blockquote>"
                )

            media_group.append(
                InputMediaPhoto(
                    media=img,
                    caption=caption
                )
            )

        await client.send_media_group(
            chat_id=message.chat.id,
            media=media_group,
            reply_to_message_id=message.id
        )

        await pros.delete()

    except Exception as e:
        logger.error(f"Bing IMG error:\n{traceback.format_exc()}")

        await pros.edit(
            f"{emo.gagal}<b>Error:</b>\n"
            f"<blockquote><code>{e}</code></blockquote>"
        )

    return


async def maker_img_cmd(client, message):
    em = Emoji(client)
    await em.get()
    if len(message.command) < 2:
        return await message.reply(
            f"{em.gagal}**Please give me command and reply to photo!!\nExample: `{message.text.split()[0]} nude` (reply photo).**"
        )
    proses = await animate_proses(message, em.proses)
    reply = message.reply_to_message
    if message.command[1] == "sertifikat":
        if len(message.command) < 3:
            return await proses.edit(
                f"{em.gagal}**Please give text!!\nExample: `{message.text.split()[0]} sertifikat anak babi`.**"
            )
        text = " ".join(message.command[2:])
        params = {"text": text}
        url = "https://api.siputzx.my.id/api/m/sertifikat-tolol"
        response = await Tools.fetch.post(url, json=params)
        if response.status_code == 200:
            if not response.content:
                return await proses.edit(f"{em.gagal}**Please try again.**")
            file_path = f"sertifikat_{uuid.uuid4().hex}.jpg"
            with open(file_path, "wb") as f:
                f.write(response.content)
            await message.reply_photo(
                file_path, caption=f"{em.sukses}<b>Succesfully generate image.</b>"
            )
            os.remove(file_path)
            return await proses.delete()
        else:
            return await proses.edit(
                f"{em.gagal}<b>Failed to generate image. Please try again later.</b>"
            )
    elif message.command[1] == "xnxx":
        if len(message.command) < 3:
            return await proses.edit(
                f"{em.gagal}**Please give text!!\nExample: `{message.text.split()[0]} xnxx skandal viral`.**"
            )
        text = " ".join(message.command[2:])
        if not message.reply_to_message.media:
            return await proses.edit(f"{em.gagal}**Please reply photo!!**")
        media = await reply.download()
        async with aiofiles.open(media, mode="rb") as file:
            file_data = await file.read()
        url = "https://api.siputzx.my.id/api/canvas/xnxx"
        async with aiohttp.ClientSession() as session:
            form = aiohttp.FormData()
            form.add_field("title", text)
            form.add_field(
                "image", file_data, filename="image.jpg", content_type="image/jpeg"
            )

            async with session.post(url, data=form) as response:
                if response.status != 200:
                    return await proses.edit(f"{em.gagal}**Please try again later!!**")
                file_path = f"canvas{uuid.uuid4().hex}.jpg"
                with open(file_path, "wb") as f:
                    f.write(await response.read())
                await proses.delete()
                return await message.reply_photo(file_path)
    else:
        return await proses.edit(
            f"{em.gagal}**Please give me command and reply to photo!!\nExample: `{message.text.split()[0]} nude` (reply photo).**"
        )


async def dalle_cmd(client, message):
    em = Emoji(client)
    await em.get()
    proses = await animate_proses(message, em.proses)
    prompt = client.get_text(message)
    if not prompt:
        return await proses.edit(
            f"{em.gagal}**Please reply to a message containing the prompt!\n"
            f"Example: `{message.text.split()[0]} beautiful japanese girl`**"
        )
    headers = {"mg-apikey": API_MAELYN}
    params = {"prompt": prompt, "resolution": "Square"}
    url = "https://api.maelyn.sbs/api/txt2img/dallexl"
    response = await Tools.fetch.get(url, headers=headers, params=params)
    if response.status_code == 200:
        try:
            data = response.json()["result"].get("url")
            img = await Tools.get_media_data(data, "jpg")
            caption = f"{em.sukses}<b>Successfully generate image.</b>"
            await message.reply_photo(img, caption=caption)
            return await proses.delete()
        except Exception:
            return await proses.edit(
                f"{em.gagal}<b>Failed to generate image. Please try again later.</b>"
            )
    else:
        return await proses.edit(
            f"{em.gagal}<b>Failed to generate image. Please try again later.</b>"
        )


async def startnest_cmd(client, message):
    em = Emoji(client)
    await em.get()
    text = client.get_text(message)
    if not text:
        return await message.reply(
            f"{em.gagal} **Please reply to message text or give message!\nExample: `{message.text.split()[0]} beautiful girl`.**"
        )
    pros = await animate_proses(message, em.proses)
    try:
        url = f"https://api.maelyn.sbs/api/txt2img/startnest?prompt={text}&apikey={API_MAELYN}"
        result = await Tools.fetch.get(url)
        if result.status_code == 200:
            image = result.json()["result"][0]
            await message.reply_photo(image)
            return await pros.delete()
        else:
            return await pros.edit(f"{em.gagal}**ERROR:**{result.status_code}")
    except Exception as e:
        await message.reply(f"{em.gagal}**ERROR:** {str(e)}")
        return await pros.delete()


async def remini_cmd(client, message):
    em = Emoji(client)
    await em.get()
    prs = await animate_proses(message, em.proses)
    rep = message.reply_to_message or message
    if len(message.command) < 2 and not rep:
        return await prs.edit(f"{em.gagal}**Please reply to image or give link.!!**")
    if rep and rep.media:
        arg = await Tools.maelyn_upload(message)
    else:
        arg = client.get_text(message)
        if not arg.startswith("https://"):
            return await prs.edit(
                f"{em.gagal}**Please give valid link or reply media**"
            )
    url = f"https://api.maelyn.sbs/api/img2img/remini?url={arg}&apikey={API_MAELYN}"
    respon = await Tools.fetch.get(url)
    await prs.edit(f"{em.proses}**Scanning of image...**")
    if respon.status_code == 200:
        data = respon.json()["result"]
        try:
            await prs.delete()
            url = data.get("url")
            type = data.get("type")
            size = data.get("size")
            expired = data.get("expired")
            return await message.reply_photo(
                url,
                caption=f"{em.sukses}**Type**: {type}\n**Size**: {size}\n**Expired**: {expired}",
            )
        except Exception as er:
            await prs.delete()
            return await message.reply(f"{em.gagal}**ERROR:** {str(er)}")
    else:
        return await prs.edit(f"**{em.gagal}Please try again: {respon.status_code}!**")


async def genai_cmd(client, message):
    em = Emoji(client)
    await em.get()
    proses = await animate_proses(message, em.proses)
    prompt = client.get_text(message)
    if not prompt:
        return await proses.edit(
            f"{em.gagal}**Please reply to a message containing the prompt!\n"
            f"Example: `{message.text.split()[0]} beautiful japanese girl`**"
        )
    try:
        url = f"https://api.maelyn.sbs/api/txt2img/realistic?prompt={prompt}&resolution=Portrait&apikey={API_MAELYN}"
        result = await Tools.fetch.get(url)
        if result.status_code != 200:
            return await proses.edit(f"{em.gagal}**Please try again later!!**")
        data = result.json().get("result", [])
        if not data:
            return await proses.edit(f"{em.gagal}**No image found!!**")
        image = data[0]
        await message.reply_photo(image)
        return await proses.delete()
    except Exception as e:
        await message.reply(f"{em.gagal}**ERROR:** {str(e)}")
        return await proses.delete()
